spring.application.name=ianus-plugin
opennms.base-url=http://localhost:8980/opennms
opennms.username=admin
opennms.password=admin
prometheus.base-url=http://localhost:9090/api/v1
#prometheus.username=
#prometheus.password=
#prometheus.connect-timeout=5s
#prometheus.read-timeout=30s
#prometheus.collector.interval-ms=300000
#prometheus.collector.queries=up